title: Default Page
preset: page
pages: false
files: false
fields:
  text:
    label: Text
    type: editor
    size: large
    allowed: 
      - h1
      - h2
      - h3
      - paragraph
      - ul

