title: Service
icon: 💡
preset: page

fields:
  intro:
    label: Intro für Servicebereich
    type: editor
    allowed: 
      - h1
      - h2
      - paragraph
  tickets:
    label: Ticket Erklärung
    type: editor
    allowed: 
      - h2
      - paragraph
  ticketlinks:
    label: Links zum Ticket-Service
    type: structure
    fields:
      name: 
        type: text
      link:
        type: text
  feedback:
    label: Text Feedback-Button
    type: editor
    allowed:
      - h2
      - paragraph
  download:
    label: Download Erklärung
    type: editor
    allowed: 
      - h2
      - paragraph
  press:
    label: Presse Erklärung
    type: editor
    allowed: 
      - h2
      - paragraph
  pressContact:
    label: Presse Kontakt
    type: editor
    allowed: 
      - paragraph
  contact:
    label: Kontaktadresse
    type: editor
    allowed: 
      - h2
      - paragraph


            